name: Follow-up Workflow

on:
  workflow_run:
    workflows: ["Pull Request Actions"]  # The name of the first workflow
    types:
      - completed  # Trigger when the first workflow completes

jobs:
  follow-up-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Follow-up Action
      run: echo "The first workflow has completed. This is the follow-up workflow!"
